config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  resources :event_attendees, only: [:new, :create]
  
  get '/auth/facebook/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy'

  get '/signup' => 'users#new', as: '/signup'
  get 'login' => 'sessions#new'
  post '/login' => 'sessions#create'
  

  resources :users do 
    resources :statements, only: [:show, :index]
  end  

  resources :users do 
    resources :events, only: [:show, :index]
  end  
    
  get '/user/info' => 'users#info'
  patch '/user/info' => 'users#location_info'

  resources :welcome, only: [:home]  

  resources :statements

  resources :comments

  resources :categories

  resources :events
  
end

   

app/models/user.rb
class User < ApplicationRecord

  has_many :event_attendees, foreign_key: 'attendee_id'
  has_many :attending_events, through: :event_attendees, source: :event
  has_many :created_events, class_name: 'Event', foreign_key: :creator_id, source: :event, dependent: :destroy
  has_many :comments
  has_many :statements

  before_save {self.email = email.downcase }

  validates_presence_of :name, :email 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }

  validates :email, uniqueness: true  

  has_secure_password 

  def self.party
    party = ['democrat', 'independent', 'libertarian', 'socialist', 'I Hate Republicans']
  end 

  def logged_in?
    session[:user_id] != nil
  end  

  def self.current 
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end  

  def statement_count
    self.statements.count
  end  

end    

app/controllers/users_controller.rb
 class UsersController < ApplicationController

  def index 
    @users = User.all
  end   

  def new
    @user = User.new
  end

  def info
    @user = current_user
  end 

  def location_info
    @user = current_user
    @user.update(location_params)
    if @user.save 
      redirect_to @user 
    else 
      render "info" 
    end   
  end  
  
  def create 
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save 
        flash[:success] = "User #{@user.name} was successfully created."
        session[:user_id] = @user.id
        format.html { redirect_to root_path } 
        format.json { render :show, status: :created, location: @user }    
      else 
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end      
  end  

  def show
    @user = User.find(params[:id])
    @events = Event.in_state_events
  end  

  def edit
    @user = User.find(params[:id])
  end 
  
  def update  
    @user = User.find(params[:id]) 
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :created, location: @user }    
      else 
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end      
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end  

private 

  def user_params
    params.require(:user).permit(:event_id, :name, :email, :password, :password_confirmation, :city, :state, :party_affiliation, :statement_id)
  end  

  def location_params
    params.require(:user).permit(:state, :city, :party_affiliation)
  end  

end

app/helpers/users_helper.rb
module UsersHelper

  def display_user(statement)
    statement.user.nil? ? 'Anonymous' : link_to(statement.user_name, user_path(statement.user))
  end

end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(user) do |f| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
   
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" %>
   
      <%= f.label :state %>
      <%= f.text_field :state, class: "form-control" %><br>

      <%= f.label :party_affiliation %>
      <%= f.select :party_affiliation, User.party, class: "form-control" %><br><br>
  
      <button type="submit" class="btn btn-primary">Submit</button> 
    <% end %><br>
    

app/views/users/edit.html.erb
<div class="new-event">
  <div class="col-md-9 col-md-offset-3">
    <h2>Update personal info</h2>
  </div>  
</div>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.name %><br>
  <%= user.party_affiliation %><br>
  <%= user.city %><br>
  <%= user.state %><br>
<% end %>

app/views/users/info.html.erb
<h3>Please provide location information</h3>
<%= form_for @user, url: { action: :location_info } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>  
    </div>
  <% end %>  

<div class="container">

  <form>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :party_affiliation %>
      <%= f.select :party_affiliation, User.party, class: "form-control" %>
    </div>
  
    <%= button_to "Submit", user_info_path(current_user), method: :patch %>

    <!-- <button type="submit" class="btn btn-primary">Submit</button> -->

  </form>   
<% end %>  
</div>  

app/views/users/new.html.erb
<div class="new-event">
  <div class="col-md-9 col-md-offset-3">
    <h2>Sign up for Organized Resistance</h2>
  </div>  
</div>
<%= render 'form', user: @user %>

<%= link_to "Sign in with Facebook", "/auth/facebook" %>

app/views/users/show.html.erb
<% if logged_in? %>
  <div class="profile">
    <h2><%= @user.name %>'s Profile</h2>
  </div>  
  
  <ul>
    <li><p>Party Affiliation: <%= @user.party_affiliation %></p></li>
    <li><p>City: <%= @user.city %></p></li> 
    <li><p>State: <%= @user.state %></p></li>
  </ul>

  <% if current_user.id == @user.id %>
  
    <div class="users">
      <h2>Events you have signed up for:</h2>  
  
        <ul>
          <% @user.attending_events.uniq.each do |event| %>
            <li><%= link_to event.title, event_path(event) %></li>
          <% end %>  
        </ul><br>
  
        <h2>Your created events:</h2>
        <ul>
        <% @user.created_events.each do |e| %>
          <h3><li><%= link_to e.title, event_path(e) %></li></h3>

          <h4>Attending:</h4>
          
          <% e.attendees.uniq.each do |attendee| %>
            <li><%= attendee.name %> - <%= attendee.email %></li>

          <% end %>  
        <% end %>  
      </ul><br>
  
        <h2>Your statements:</h2>
        <ul>
        <% @user.statements.each do |statement| %>
          <li><%= link_to statement.headline, user_statement_path(@user, statement) %></li>
        <% end %>  
      </ul><br>

      <h2>Events in your state:</h2>
      <ul>
        <% @events.each do |event| %>
          <li><%= link_to event.title, event_path(event) %></li>
        <% end %><br>
      </ul>

      <%= link_to "Update account", edit_user_path(@user) %><br>
      <%= link_to "Delete your account", user_path(@user),
                                              method: :delete,
                                              data: { confirm: 'Are you sure?' } %>

  <% else %>  
    <h2>Events Created by <%= @user.name %>:</h2>
    <ul>
      <% @user.created_events.each do |e| %>
        <li><%= link_to e.title, user_event_path(@user, e) %></li>
      <% end %>  
    </ul>

    <h2>Statements by <%= @user.name %>:</h2>
    <ul>
      <% @user.statements.each do |statement| %>
        <li><%= link_to statement.headline, user_statement_path(@user, statement) %></li>
      <% end %>  
    </ul>
    </div>
  <% end %>
<% else %>  
  <p>You must be signed in to view this page</p>
<% end %>


  

  