config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  resources :event_attendees, only: [:new, :create]
  
  get '/auth/facebook/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy'

  get '/signup' => 'users#new', as: '/signup'
  get 'login' => 'sessions#new'
  post '/login' => 'sessions#create'
  

  resources :users do 
    resources :statements, only: [:show, :index]
  end  

  resources :users do 
    resources :events, only: [:show, :index]
  end  
    
  get '/user/info' => 'users#info'
  patch '/user/info' => 'users#location_info'

  resources :welcome, only: [:home]  

  resources :statements

  resources :comments

  resources :categories

  resources :events
  
end

   

app/models/statement.rb
class Statement < ActiveRecord::Base

  belongs_to :user
  belongs_to :event
  has_many :comments
  has_many :statement_categories
  has_many :categories, through: :statement_categories

  validates_presence_of :headline, :content

  def comment_count
    self.comments.count
  end    

  def user_name
    self.try(:user).try(:name)
  end  

  def user_name=(name)
    user = User.find_or_create_by(name: name)
    self.user = user
  end    

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      if category_attribute["name"] != ""
        category = Category.find_or_create_by(category_attribute) 
      end  
      self.statement_categories.build(category: category)
    end  
  end    

end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController

  def index
    if params[:user_id]
      @statements = User.find_by(id: params[:user_id]).statements
    else
      @statements = Statement.all 
    end    
  end  

  def new
   @statement = Statement.new
  end
  
  def create 
    @statement = current_user.statements.build(statement_params)
    if @statement.save!
      redirect_to statement_path(@statement)
    else 
      render "new"
    end    
  end 

  def show
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      @statement = @user.statements.find_by(id: params[:id])
      @comment = Comment.new(statement: params[:statement_id])
    else 
      @statement = Statement.find(params[:id])      
      @comment = Comment.new(statement: params[:statement_id])
    end  
  end  

  def edit 
    @statement = Statement.find(params[:id]) 
  end 

  def update 
    @statement = Statement.find(params[:id])
    if @statement.update(statement_params) 
      redirect_to statement_path(@statement)
    else 
      render 'edit'  
    end
  end  

  def destroy
    @statement = Statement.find(params[:id])
    @statement.destroy

    redirect_to user_path(current_user)
  end  

private 

  def statement_params
    params.require(:statement).permit(:content, :headline, :user_name, category_ids: [], categories_attributes: [:name])
  end   

end

app/helpers/statements_helper.rb
module StatementsHelper

    

end

app/views/statements/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(statement) do |f| %>
      <% if statement.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(statement.errors.count, "error") %> prohibited this statement from being saved:</h2>
      <ul>
      <% statement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  

    <%= f.label :headline %> 
    <%= f.text_field :headline, class: "form-control" %><br>
  
    <%= f.text_area :content, class: "form-control", rows: "20", placeholder: "Write statement here" %>
  
  <div class="new-event">
    <h2>Categories</h2>
  </div>  

  <div class="checkbox-inline">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>

  <div class="cats-field">
    <%= f.fields_for :categories, @statement.categories.build do |ff| %>
      <%= ff.text_field :name, placeholder: "New Category", allow_blank: false %>
    <% end %>  
  </div>  
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>  

<% end %> 

app/views/statements/edit.html.erb
<% if logged_in? %>
  <div class="new-event">
    <div class="col-md-6 col-md-offset-3">
      <h2>Edit Statement</h2>
      <h2><%= @statement.headline %></h2>
    </div> 
  </div>    
  <%= render partial: 'form', locals: { statement: @statement } %>
<% else %>  
  You must be signed in to view this page
<% end %>

app/views/statements/index.html.erb
<div class="date-events">
  All Statements
</div>

<div class="container">
  <div class="col-md-8">
    <ul class="list-group">
      <% @statements.each do |statement| %>
        <li><p>Author: <%= display_user(statement) %></p></li>
        <li><p>Created On: <%= statement.created_at.strftime("%m-%d-%Y") %></p></li>
        <li><p><%= link_to statement.headline, statement_path(statement) %></p></li><br><br>
      <% end %>
    </ul>
  </div>
</div>  

app/views/statements/new.html.erb
<% if logged_in? %>
    <div class="new-event">
      <div class="col-md-8 col-md-offset-3">
        <h2>Make A Statement</h2>
      </div>  
    </div>    
    <%= render partial: "form", statement: Statement.new, locals: { statement: @statement } %>
<% else %>  
  <p>Must be signed in to view this page</p>
<% end %>  

app/views/statements/show.html.erb
<div class="new-event">  
  <div class="col-md-8 col-md-offset-2">
  <h2>Resistance Statement</h2>
  </div>
</div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="blog-post">
            <h2 class="blog-post-title"><%= @statement.headline%></h2>
            <p class="blog-post-meta"><%=@statement.created_at.strftime("%m-%d-%Y") %> by <%= display_user(@statement) %></p>
            <p><%= @statement.content %></p>
          <% if current_user == @statement.user %>
            <%= link_to "Edit Statement", edit_statement_path(@statement) %><br>
          <% end %><br>

<div class="categories">
  <p>Categories: <% @statement.categories.collect do |category| %>
    <%= link_to category.name, category_path(category) %>
  <% end %></p>
</div>

<%= form_for(@comment, html: {class: "form-horizontal", role: "form"}) do |f| %>
  <%= f.hidden_field :statement_id, value: @statement.id %>

  <div class="form-group">

    <div class="col-sm-8">
      <%= f.text_area :content, rows: 3, class: "form-control", placeholder: "Enter comment here", autofocus: true %>
    </div>
  </div>    
  <p><%= f.submit class: "btn btn-primary" %></p>
<% end %>


<div class="comments">
  <ul>
    <% @statement.comments.each do |comment| %>
      <% binding.pry %>
      <li><p><b><%= comment.user_name %> Says:</b> <%= comment.content %></p></li>
    <% end %>  
  </ul>  
</div>

<%= link_to "All Statements", statements_path %><br>

<%= link_to "Delete statement", statement_path(@statement),
                                              method: :delete,
                                              data: { confirm: 'Are you sure?' } %>