config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  resources :event_attendees, only: [:new, :create]
  
  get '/auth/facebook/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy'

  get '/signup' => 'users#new', as: '/signup'
  get 'login' => 'sessions#new'
  post '/login' => 'sessions#create'
  

  resources :users do 
    resources :statements, only: [:show, :index]
  end  

  resources :users do 
    resources :events, only: [:show, :index]
  end  
    
  get '/user/info' => 'users#info'
  patch '/user/info' => 'users#location_info'

  resources :welcome, only: [:home]  

  resources :statements

  resources :comments

  resources :categories

  resources :events
  
end

   

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    
  end  

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<h2>Organized Resistance.</h2>
  <link href="https://fonts.googleapis.com/css?family=Raleway:200,100,400" rel="  stylesheet" type="text/css" />
  <%= stylesheet_link_tag "welcome" %>

<h1>
  <span
     class="txt-rotate"
     data-period="2000"
     data-rotate='[ "RESIST TRUMP EVERYWHERE" ]'></span>
</h1>
<h2>Organize Against Donald Trump</h2>
  <p>Organize local events and become part of the resistance. Gather friends and neighbors to amplify your voice and make it known that none of this is okay. Write an article(statement) about an event or the latest Trump outrage. Make your voice heard even if you can't attend an event. </p>

<body class="root-body">

    
      <div style="float:left;">
        <%= button_to "View All Events", events_path, class: 'btn-group', method: 'get', action: '/events' %>
      </div>  
      <div style="float:left;">
        <%= button_to "View All Statements", statements_path, class: 'btn-group', method: 'get', action: '/statements' %>
      </div>
      <div style="float:left;">  
        <%= button_to "Create an event", new_event_path, class: 'btn-group', method: 'get', action: '/events/new' %>
      </div>
      <div style="float:left;">  
        <%= button_to "Write a statement", new_statement_path, class: 'btn-group', method: 'get', action: '/statements/new' %>    
      </div>    

</body><br><br>