config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  resources :event_attendees, only: [:new, :create]
  
  get '/auth/facebook/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy'

  get '/signup' => 'users#new', as: '/signup'
  get 'login' => 'sessions#new'
  post '/login' => 'sessions#create'
  

  resources :users do 
    resources :statements, only: [:show, :index]
  end  

  resources :users do 
    resources :events, only: [:show, :index]
  end  
    
  get '/user/info' => 'users#info'
  patch '/user/info' => 'users#location_info'

  resources :welcome, only: [:home]  

  resources :statements

  resources :comments

  resources :categories

  resources :events
  
end

   

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :creator, class_name: 'User'
  has_many :event_attendees
  has_many :attendees, through: :event_attendees
  has_many :statements

  accepts_nested_attributes_for :statements 

  validates_presence_of :title, :description, :date, :time, :street_address, :city, :state

  def self.past_events
    self.where("date < ?", Time.now.beginning_of_day)
  end  

  def self.future_events
    self.where("date > ?", Time.now.beginning_of_day)
  end   

  def self.in_state_events
    self.where("state = ?", User.current.state) if User.current
  end

  def attending?
    User.current.attending_events.include?(self)
  end   

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
 
  def index
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      if @user.nil?
        redirect_to users_path
        flash[:alert] = "User not found"
      else
        @events = @user.created_events
      end
    else      
      @past_events = Event.past_events
      @future_events = Event.future_events
    end  
  end  

  def new
    @event = Event.new 
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to event_path(@event)
      flash[:success] = "Event Created Successfully"
    else 
      render 'new'
    end    
  end
    
  def show
    if current_user == nil
      redirect_to login_path
      flash[:alert] = "You must be signed in to view an event"
    else    
      if params[:user_id]
        @user = User.find_by(id: params[:user_id])
        @event = @user.created_events.find_by(id: params[:id])
        if @event.nil?
          redirect_to user_events_path(@user)
          flash[:alert] = "Event not found"
        end  
      else  
        @event = Event.find(params[:id])
        @attending = current_user.attending_events
      end  
    end
  end  

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else 
      render "edit"
    end    
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

private 

  def event_params
    params.require(:event).permit(:title, :street_address, :location_name, :city, :state, :title, :description, :date, :time, :creator_id, statements_attributes: [:headline, :content])
  end  

  # def require_login
  #   return head(:forbidden) unless session.include? :user_id
  # end  

end

app/helpers/events_helper.rb
module EventsHelper 


end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(event) do |f| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>    

    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>

    <%= f.label :date_of_event %>
    <%= f.date_field :date, class: "form-control" %>

    <%= f.label :time %>
    <%= f.time_field :time, class: "form-control" %>

    <%= f.label :location_name %>
    <%= f.text_field :location_name, class: "form-control" %>
    
    <%= f.label :street_address %>
    <%= f.text_field :street_address, class: "form-control" %>
    
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
    
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %><br>

      <button type="submit" class="btn btn-primary">Submit</button> 
    <% end %>

app/views/events/edit.html.erb
<% if logged_in? %>
  <div class="new-event">
    <div class="col-md-8 col-md-offset-3">
      <h2>Edit Your Event</h2>
    </div>    
  </div> 
  <%= render partial: "form", locals: { event: @event } %>
<% else %>
  Must be signed in to vew this page
<% end %>  

app/views/events/index.html.erb
<% if @events != nil %>
  <h2><%= @user.name %>'s events</h2>
  <ul>
    <% @events.each do |event| %>
      <li><p><%= link_to event.title, user_event_path(@user, event) %></p></li> 
    <% end %>  
  </ul>
<% else %>  

<div class="date-events">
  Future Events
</div>  
  <ul>
    <% @future_events.each do |event| %>
      <li><p>Title: <%= link_to event.title, event_path(event) %></p></li> 
      <li><p>Date: <%= event.date %></p></li>
      <li><p>Time: <%= event.time.strftime("%l:%M %p") %></p></li>
      <li><p>Description <%= event.description %></p></li>
      <li><p>Creator: <%= link_to event.creator.name, user_path(event.creator) %></p>  </li><br>
      <%= button_to 'Attend This Event', event_attendees_path(event_id: event), class: 'btn-group' %><br>
    <% end %>   
  </ul>  

<div class="date-events">
  Past Events
</div>  
  <ul>
    <% @past_events.each do |event| %>
      <li><p>Title <%= link_to event.title, event_path(event) %></p></li> 
      <li><p>Date: <%= event.date %></p></li>
      <li><p>Description <%= event.description %></p></li>
      <li><p>Creator: <%= link_to event.creator.name, user_event_path(event.creator, event) %></p></li>
    <% end %>  
  </ul> 


<% end %>

app/views/events/new.html.erb
<% if logged_in? %>
  <div class="new-event">
    <div class="col-md-8 col-md-offset-3">
      <h2>Create A New Event</h2>
    </div>    
  </div> 
  <%= render partial: "form", locals: { event: @event } %>
<% else %>
  <p>Must be signed in to view this page</p>
<% end %>  

app/views/events/show.html.erb
<div class="new-event">
  <h2>Event</h2>
</div> <br> 

<ul>
  <div class="title">
    <li><p>Title: <%= @event.title %></p></li>
  </div>
  <li><p>Creator: <%= link_to @event.creator.name, user_events_path(@event.creator)%></p></li> 
  <li><p>Date: <%= @event.date.strftime("%B %dth, %C%y") %></p></li>
  <li><p>Time: <%= @event.time.strftime("%l:%M %p") %></p></li>  
  <li><p>Description:  <%= @event.description %></p></li> 
  <li><p>Location:  <%= @event.location_name %></p></li>
  <li><p>Address:  <%= @event.street_address %></p></li>
  <li><p>City:  <%= @event.city %></p></li> 
  <li><p>State:  <%= @event.state %></p></li>  
  <li><p>Attendees:</b> <%= @event.attendees.uniq.count %></p></li>
</ul> <br>

  <% if current_user.id == @event.creator.id %>
    <%= link_to "Edit event details", edit_event_path(@event) %><br>  
    <%= link_to "Delete this event", event_path(@event),
                                              method: :delete,
                                              data: { confirm: 'Are you sure?' } %>
  <% else %>
    <%= button_to 'Attend This Event', event_attendees_path(event_id: @event), class: "btn-group" %>
  <% end %><br>

<div class="attend">
  <% if @event.attending? %>
    <p>You have signed up for this event</p> 
  <% end %>
</div>  